### ISSUE TITLE
Configuration errors in pgxc_ctl.conf cause segment fault.

### ISSUE THREAD

**Issue by shenlongxing** [postgres-x2/postgres-x2#103]
I deploy two coordinators and two datanodes in the pgxc_ctl.conf. 
I get a core dump when starting up pgxc.

[postgres@gorilla1 pgxc_ctl]$ pgxc_ctl
Installing pgxc_ctl_bash script as /home/postgres/pgxc_ctl/pgxc_ctl_bash.
Installing pgxc_ctl_bash script as /home/postgres/pgxc_ctl/pgxc_ctl_bash.
Reading configuration using /home/postgres/pgxc_ctl/pgxc_ctl_bash --home /home/postgres/pgxc_ctl --configuration /home/postgres/pgxc_ctl/pgxc_ctl.conf
Finished to read configuration.
   *******\* PGXC_CTL START ***************

Current directory: /home/postgres/pgxc_ctl
PGXC init all
Initialize GTM master
gtm: no process killed
The files belonging to this GTM system will be owned by user "postgres".
This user must also own the server process.

fixing permissions on existing directory /data/pgxc_data/gtm ... ok
creating configuration files ... ok

Success. You can now start the GTM server using:

```
gtm -D /data/pgxc_data/gtm
```

or
    gtm_ctl -Z gtm -D /data/pgxc_data/gtm -l logfile start

waiting for server to shut down.... done
server stopped
Done.
Start GTM master
gtm_ctl: PID file "/data/pgxc_data/gtm/gtm.pid" does not exist
Is server running?
server starting
Initialize all the coordinator masters.
Initialize coordinator master coord1.
Initialize coordinator master coord2.
Segmentation fault

The error comes from pgxc_ctl.conf. I deploy two coordinators, but the element number of coordSpecificExtraConfig/coordSpecificExtraPgHba is one. And gtm_proxy/datanode have the same bug.

**Comment by koichi-szk** [comment]
Went to all the relevant branches.
