### ISSUE TITLE
Search Path Propagation Issue

### ISSUE THREAD

**Issue by koichi-szk** [postgres-x2/postgres-x2#105]
Submitted by David E.Wheeler, 2014-01-31.

See [sourceforge bug tracker](https://sourceforge.net/p/postgres-xc/bugs/473/) for details.

I have a script that looks like this:

```
BEGIN;
SET client_min_messages TO warning;
SET search_path TO geo;

CREATE TABLE continents (
    code      CHARACTER(2) PRIMARY KEY,
    continent TEXT         NOT NULL
);
```

I ran this against a coordinator, and it seemed to work. But when I tried to select from the table, XC said it could not be found. \d geo.continents shows it, but only on the coordinator on which I ran the script. If I connect to any other coordinator or any data node, the continents table is in the public schema rather than the geo schema.

Bug? I don't see any mentinon of SET not being distributed in the SET docs. I can work around it by schema-qualifying objects, but would rather not have to.

**Comment by scarbrofair** [comment]
For this issue, I think it will make sense if we can Propagate GUCs to other coordinators and datanodes when users try to change GUCs. For example, some times, we want to change the work_mem of current session,  we need to change the work_mem on all the other nodes connected by current session.

**Comment by koichi-szk** [comment]
At present, set command propagates to all the child sessions.    Pooler
records each connection's set command and replay it when pooled connection
is used from different parent connection.

I'm considering to improve pgxc_ctl to propagate changes to postgresql.conf.

Thank you;

---

Koichi Suzuki
https://www.linkedin.com/in/koichidbms

2015-08-10 16:04 GMT+09:00 scarbrofair notifications@github.com:

**Comment by scarbrofair** [comment]
And, for this issue, should we add the schema to table name when deparse the Query?

**Comment by koichi-szk** [comment]
In internal deparse, yes, XC is adding schema name to full qualified name.
  What scene do you mean to deparse?

---

Koichi Suzuki
https://www.linkedin.com/in/koichidbms

2015-08-10 16:26 GMT+09:00 scarbrofair notifications@github.com:

**Comment by scarbrofair** [comment]
Sorry for miss something, I mean for the case such as: set search_path to some_schema; select \* from  table_name.

**Comment by koichi-szk** [comment]
Sorry, I've not reviewed this code.   Because set search_pat is included in
the regression test and all these pass, I believe this is also handled
properly.

---

Koichi Suzuki
https://www.linkedin.com/in/koichidbms

2015-08-10 16:38 GMT+09:00 scarbrofair notifications@github.com:

**Comment by scarbrofair** [comment]
OK, I think we can close it, I verify it with X2 of latest version.
