### ISSUE TITLE
 The pooler process doesn't exit some times after excuting "stop all"

### ISSUE THREAD

**Issue by koichi-szk** [postgres-x2/postgres-x2#118]
Submitted by Peace Zone, 2014-07-21.

See [sourceforge bug tracker](https://sourceforge.net/p/postgres-xc/bugs/487/) for details.

The pooler process doesn't exit after I execute "stop all" command.

When gdbs the process, I find it stops at this place : poolmgr.c

```
2368 retval = select(nfds + 1, &rfds, NULL, NULL, NULL);
2369 if (shutdown_requested)
```

When the server_id is not changed, the select will wait forever. 
The routine has no chance to echo "shutdown_requested"

Does it need to add a "timeout" in select routine?

The Syslogger process has the same problem.

**Related**

Bugs: #487

**Comment by xuegang** [comment]
I have found the problem.
My analyze as follows:
   if pooler process receive term signal. then set shutdown_requested=true

  The reason why the pooler process doesn't exit as follows:
      if you receive term signal before select() function. then you will wait in select functon().

```
  You can recreat problem using gdb.  Add Breakpoint before select function. and send term singal 
   to pooler process. You will find that pooler can not exit.
```

  My soluction as follows. Run shutdown_requested before select.

```
          if (shutdown_requested)
    {
        for (i = agentCount - 1; i >= 0; i--)
        {
            PoolAgent  *agent = poolAgents[i];

            agent_destroy(agent);
        }
        while (databasePools)
            if (destroy_database_pool(databasePools->database,
                                      databasePools->user_name) == 0)
                break;
        close(server_fd);
        exit(0);
    }

           retval = select(nfds + 1, &rfds, NULL, NULL, NULL);
```

I have test it. Everything is OK.

**Comment by koichi-szk** [comment]
Thanks a lot for the fix.   Could you publish pull request or send me a patch?   I need to see what branches the fix should/can go before committing.   The outline of the fix seems okay.

Thanks a lot.
Koichi

**Comment by xuegang** [comment]
I have sent pull request to you. Pleae review it. If any problem. Please let me know.

**Comment by koichi-szk** [comment]
Okay.   The patch looks a bit big.   Please allow me a while to review.

**Comment by koichi-szk** [comment]
Two patches for #143 and #145 have been committed.

Closed.
