### ISSUE TITLE
Some distributed transactions can not rollback

### ISSUE THREAD

**Issue by xuegang** [postgres-x2/postgres-x2#129]
recreate steps as follows: 
    1).prepare a transaction "test" in session 1.
    2).restart pgxc cluster before commit "test"
    3).connect to session2 and prepared "test"

**Comment by koichi-szk** [comment]
You are correct.   We can have similar situation when a code crashes.   I think pgxc_clean takes care of this situation.   Hope you try this.

Thank you;
Koichi

**Comment by koichi-szk** [comment]
Now close this.   Can reopen when another case is found.
