### ISSUE TITLE
 There are some error message when I use pgbench to test pgxc

### ISSUE THREAD

**Issue by xuegang** [postgres-x2/postgres-x2#130]
There are some error message when I use pgbench to test pgxc error message as follows:

```
  Xid is invalid.                                                                                                     
  ERROR: could not receive data from client: Connection reset by peer can not connect to GTM: 
  Connection reset by peer
```

   But after I restart gtm proxy. Everything is OK.

**Comment by koichi-szk** [comment]
Were gtm proxy configured and started when you ran pgbench fir the first time?   I understand it is not easy to reproduce the case.

When you see such error, please see if gtm proxy is running and other transaction can be handled.

Thank you;
Koichi

**Comment by koichi-szk** [comment]
Not reproducible.   Can reopen when more specific report is posted.
