### ISSUE TITLE
Data inconsistent between datanode master and datanode slave when I insert some records into  replication  table. A record is visible

### ISSUE THREAD

**Issue by xuegang** [postgres-x2/postgres-x2#131]
Recreate steps as follows:

   1).psql -h 192.168.34.129 -p 20004 postgres -c "create table t1(id int) distribute by replication;" 
   2).insert some recodes into t1
   3). psql -h192.168.34.130 -p 20009 postgres -c "select count(_) from t1;" -t . master result is 4000
      psql -h192.168.34.129 -p 20009 postgres -c "select count(_) from t1;" -t . slave  result is 3999

   4).use "select xmin from t1". I found that slave miss a recode(xmin=xmin=3805)
   5).connect coordinate and issue "create extension pageinspect";
   6).query in master
       postgres=# SELECT \* FROM heap_page_items(get_raw_page('t1', 14)) where t_xmin=3805;  
       lp | lp_off | lp_flags | lp_len | t_xmin | t_xmax | t_field3 | t_ctid | t_infomask2 | t_infomask | t_hoff | t_bits | t_oid 
       -----------------------------------------------------------------------------------------  
       34 | 7104 | 1 | 28 | 3805 | 0 | 0 | (14,34) | 1 | 2304 | 24 | |  
       (1 row)  
       postgres=# select \* from t1 where xmin=3805;  
       id  
       1                            

   7).query in salve

```
 postgres=# SELECT * FROM heap_page_items(get_raw_page('t1', 14)) where t_xmin=3805;                                                                                                                                          
 lp | lp_off | lp_flags | lp_len | t_xmin | t_xmax | t_field3 | t_ctid | t_infomask2 | t_infomask | t_hoff | t_bits | t_oid 
 -----------------------------------------------------------------------------------------                                  
 34 | 7104 | 1 | 28 | 3805 | 0 | 0 | (14,34) | 1 | 2560 | 24 | |                                                            
 (1 row)       
```

**Comment by koichi-szk** [comment]
Hot standby is not supported in XC.  The background is: it is extremely difficult to maintain visibility and synchronize log playback timing among all the slaves.   Yes, the query is not blocked but all the query result is not accurate until the slave is promoted.

Thank you;
Koichi

**Comment by koichi-szk** [comment]
Close this.
