### ISSUE TITLE
 Some function get different value betwen master and  slave in pgxc cluster.

### ISSUE THREAD

**Issue by xuegang** [postgres-x2/postgres-x2#136]
Some function get wrong value in datanode slave.

   Some function get different value betwen master and  slave in pgxc cluster. 

These  functions as follows：
  CURRENT_DATE
  CURRENT_TIME
  CURRENT_TIMESTAMP
  CURRENT_TIME(precision)
  CURRENT_TIMESTAMP(precision)
  LOCALTIME
  LOCALTIMESTAMP
  LOCALTIME(precision)
  LOCALTIMESTAMP(precision)
  transaction_timestamp();
  now();

**Comment by koichi-szk** [comment]
It is the same cause as #131.   It's not a bug.   It's XC's spec/restriction.

Regards;
Koichi
