### ISSUE TITLE
gtm_proxy core dump

### ISSUE THREAD

**Issue by Jasonysli** [postgres-x2/postgres-x2#139]
Under concurrent situation, if thr_conn_count increases before thr_all_conns[] pointer in GTMProxy_ThreadMain loop, 
the proxy main thread maybe touch invalid ptr which is just over offset, thus, it would coredump.

**Comment by Jasonysli** [comment]
Postgres backend stuck in starting up status.
Two client connect to two different coords, both running DDL. When one coord tried to get connections to the other through pooler at the same time, pooler process stuck at connetting to each other.

**Comment by Jasonysli** [comment]
catalog corrupted.Under high pressure, when running DDL and DML, sometimes we got inconsistant catalogs among coords and datanodes.

**Comment by Jasonysli** [comment]
When running mixed SQL of DDL and DML through different coord and datanodes, it is very easy to get dead lock among nodes.

**Comment by koichi-szk** [comment]
Sorry, could you make another issue thread for issues other than gtm_proxy crash and related ones?

**Comment by Jasonysli** [comment]
Ok, sorry about it , it is my first time to use the issue.

**Comment by koichi-szk** [comment]
Don't worry.   It's okay.

---

Koichi Suzuki

2015-05-18 16:25 GMT+09:00 Jasonysli notifications@github.com:

**Comment by Jasonysli** [comment]
I just delete  other issues from gtm_proxy core dump issue. Thanks for your help.

**Comment by koichi-szk** [comment]
Thank you for the prompt action.

---

Koichi Suzuki

2015-05-18 16:30 GMT+09:00 Jasonysli notifications@github.com:

**Comment by Jasonysli** [comment]
My pleasure. Let's make pgxc popular!

**Comment by koichi-szk** [comment]
This has been merged to all the relevant branches.
