### ISSUE TITLE
Pooler process get coredump when the number of concurrent connections is large

### ISSUE THREAD

**Issue by xuegang** [postgres-x2/postgres-x2#143]
Recreate steps:

  1.psql -h 192.168.34.129 -p 30004 -Upgxc postgres -c "create database pgbench;"
  2.pgbench -h 192.168.34.129 -p 30004 -Upgxc pgbench -i -s 100 
  3.pgbench -h 192.168.34.129 -p 30004 -Upgxc pgbench -c 600 -j 20 -t 600

  Pooler process get coredump when the number of concurrent connections is large

Core was generated by `postgres: pooler process '.
  Program terminated with signal 11, Segmentation fault.
  #0 0x000000000063211a in resetStringInfo (str=0x7fff0c709380) at stringinfo.c:64
  64 str->data[0] = '\0';
  Missing separate debuginfos, use: debuginfo-install glibc-2.17-55.el7.x86_64
  (gdb) bt
  #0 0x000000000063211a in resetStringInfo (str=0x7fff0c709380) at stringinfo.c:64
  #1 0x00000000006547a2 in pool_getmessage (port=0x7f65fd4a8a34, s=0x7fff0c709380, maxlen=0) at poolcomm.c:197
  #2 0x0000000000651851 in agent_handle_input (agent=0x7f65fd4a8a30, s=0x7fff0c709380) at poolmgr.c:1122
  #3 0x0000000000653f8b in PoolerLoop () at poolmgr.c:2397
  #4 0x000000000064fd2d in PoolManagerInit () at poolmgr.c:237
  #5 0x00000000004f36d5 in AuxiliaryProcessMain (argc=2, argv=0x7fff0c7094a0) at bootstrap.c:428
  #6 0x00000000006f876e in StartChildProcess (type=PoolerProcess) at postmaster.c:5218
  #7 0x00000000006f5d4a in reaper (postgres_signal_arg=17) at postmaster.c:2757
  #8 <signal handler called>
  #9 0x00007f6612591b43 in __select_nocancel () from /lib64/libc.so.6
  #10 0x00000000006f4079 in ServerLoop () at postmaster.c:1662
  #11 0x00000000006f3981 in PostmasterMain (argc=5, argv=0x229e3f0) at postmaster.c:1369
  #12 0x000000000065aa05 in main (argc=5, argv=0x229e3f0) at main.c:206

My analysis is as below：

 Based on coredump. I found the data in StringInfoData is destroyed. So pooler get coredump. there is a memory overflow. Furthermore, with GDB, 
 I found fd is more than 1024 when pooler get coredump. So The problem is FD_SET function. FD_SET only support 1024 socket fd. If number of socket is more.Then memory  overflow. So I change select to poll function. Test result is ok.  Later, I will send pull request to you.

**Comment by koichi-szk** [comment]
Okay.   The analysis looks very reasonable.   For larger number of the nodes, we may need to consider how to deal with many FDs.

Thank you;
