### ISSUE TITLE
the uncorrect value of sync_state when select  from pg_stat_replication.

### ISSUE THREAD

**Issue by xuegang** [postgres-x2/postgres-x2#150]
select \* from g_stat_replication 
postgres=# select \* from pg_stat_replication ;
## pid | usesysid | usename | application_name | client_addr | client_hostname | client_port | backend_start | state | sent_location | write_location | flush_location | replay_location | sync_priority | sync_state

1523 | 10 | rdbdba | datanode1 | 192.168.34.132 | | 37855 | 2014-08-14 22:41:52.160202+08 | streaming | 0/7ABFCB78 | 0/7ABFCB78 | 0/7ABFCB78 | 0/7ABFCB78 | 0 | async
(1 row)

sync_state is async , but postgresql.conf is synch.

Later, I will put pull request to you.

**Comment by koichi-szk** [comment]
Thanks for the fix.

Okay, this should go.

**Comment by koichi-szk** [comment]
The patch has been committed and this issue can be closed.
