### ISSUE TITLE
pgxc_clean does not work when cleaning leftover 2pc

### ISSUE THREAD

**Issue by Jasonysli** [postgres-x2/postgres-x2#160]
When system corrupted during 2pc, we need pgxc_clean to clean up leftover transactions. But it does not work.

**Comment by koichi-szk** [comment]
How is the situation?   What option did you use?

**Comment by Jasonysli** [comment]
./pgxc_clean -v -p 30004 -h 10.215.131.218 -a

**Comment by Jasonysli** [comment]
Sorry, my mistake, It happened in pgxl, in pgxc it is ok!

**Comment by Jasonysli** [comment]
By the way, handle_response just return true or false, we don't know whether it is timeout, how about return a int value, so we can konw what happen inside?

**Comment by koichi-szk** [comment]
Yes, we should be careful about the status monitoring.    It's not only in
pgxc_clean but should cover whole X2 components as well as external one
such as network, storage, OS, etc.

We need consistent and integrated status monitoring interface.

Could we continue this analysis and discussion before implementation?   I
think we need a month or so for this preliminary work.

Any more thoughts?

---

Koichi Suzuki

2015-05-21 15:54 GMT+09:00 Jasonysli notifications@github.com:

**Comment by Jasonysli** [comment]
We will keep discussing the issue before implemation, of course.
When we try to run a SELECT across all datanodes, after do_query, XC will try to fetch tuples from datanode. FetchTuple calls pgxc_node_receive in block mode, which means no timeout just block on a datanode, regardless of other nodes. This lead to other nodes block on sending data to coord, with all locks taken. Dead locks happen more easily!  So I want  pgxc_node_receive called with timeout in FetchTuple, so we can know some node may be got stuck because of lock acquiring,  and in this case, we can just skip the stuck nodes and continue fetch data from other nodes, in this way, some dead lock may be fixed automatically.

**Comment by koichi-szk** [comment]
You have very good point.

I think it is not only timeout issue but also to improve whole performance
when huge numbers of rows have to be transferred between nodes.
One-record-at-a-time manner has severe performance limitation.   I'm
thinking to improve the pooler architecture to receive as many records as
possible without really fetch by coordinator backgrounds, group such record
(and other info) transfer between the given node pair, I mean more than one
backend are involved, and compress them to save the amount of the data and
interaction.

Now I'm doing this design work (not in explicit form yet).

Thank you;

---

Koichi Suzuki

2015-05-21 16:32 GMT+09:00 Jasonysli notifications@github.com:

**Comment by Jasonysli** [comment]
Thanks for your approving of my point. Talking about batch fetching data, PGXL have done some optimization, just by set pgxc_node_send_execute fetch row number to 1000.PGXC maybe can do that, too!

**Comment by koichi-szk** [comment]
Yes, this is my point too.   To do this with minimum cost, we need to
resolve license issue.

Thank you;

---

Koichi Suzuki

2015-05-21 16:50 GMT+09:00 Jasonysli notifications@github.com:

**Comment by Jasonysli** [comment]
Yes, license  should be resolved first.
I am thinking  issue pooler to fetch data may not be a good idea, pooler only has a single thread, but datanodes are many, pooler will be a new bottle neck, unless we use multi threads in pooler.

**Comment by koichi-szk** [comment]
I don't mean to do it as the current pooler.   To do this, pooler may need some overhaul or we need to have another layer of data transfer between a node pair, which is multi-threaded and handle a data coming from multiple nodes in parallel.

**Comment by Jasonysli** [comment]
That sounds great!

**Comment by Jasonysli** [comment]
If the design is ok, it will be my great pleasure to participate in implementing it.

**Comment by koichi-szk** [comment]
This issue has two topics, pgxc_clean and data transfer performance.   Data transfer performance will be resolved by enhancement.   See #52 and related topics.

This topics will be closed.
