### ISSUE TITLE
monitor command got a uncorrect status of datanode slave.

### ISSUE THREAD

**Issue by shenlongxing** [postgres-x2/postgres-x2#161]
I start up the pgxc cluster with one datanode master and a datanode slave. I monitor the running status   using “monitor” command. 
Here are the results:
1.monitor all
pgxc_ctl  monitor all
Installing pgxc_ctl_bash script as /home/postgres/pgxc_ctl/pgxc_ctl_bash.
Reading configuration using /home/postgres/pgxc_ctl/pgxc_ctl_bash --home /home/postgres/pgxc_ctl --configuration /home/postgres/pgxc_ctl/pgxc_ctl.conf
Finished to read configuration.
*******\* PGXC_CTL START ***************
Current directory: /home/postgres/pgxc_ctl
Running: gtm master
Running: coordinator master coord1
Running: datanode master db1
Running: datanode slave db1

2.monitor datanode slave
pgxc_ctl  monitor datanode slave
Installing pgxc_ctl_bash script as /home/postgres/pgxc_ctl/pgxc_ctl_bash.
Reading configuration using /home/postgres/pgxc_ctl/pgxc_ctl_bash --home /home/postgres/pgxc_ctl --configuration /home/postgres/pgxc_ctl/pgxc_ctl.conf
Finished to read configuration.
*******\* PGXC_CTL START ***************
Current directory: /home/postgres/pgxc_ctl
ERROR: datanode slave is not configured.

Later, I will send a  pull request on this to you.

**Comment by koichi-szk** [comment]
Okay, seems that the issue was resolved by the pull request and it has been committed to master, REL1_2_STABLE and REL1_1_STABLE branches.
