### ISSUE TITLE
Many postgres backend  process in startup status. 

### ISSUE THREAD

**Issue by xuegang** [postgres-x2/postgres-x2#163]
Maybe it is the same problem with issue140.

The backend  process is in startup status when I try to connect to coordinate. with GDB, I found that pooler process is deadlock.

My analysis is as follows:
    function  is acquire_connection in file  poolmgr.c 

```
     retry:
    /*
     * Make sure connection is ok, destroy connection slot if there is a
     * problem.
     */
    poll_result = pqReadReady((PGconn *) slot->conn);
    if (poll_result == 0)
        break;      /* ok, no data */
    else if (poll_result < 0)
    {
        if (errno == EAGAIN || errno == EINTR)
            goto retry;
        elog(WARNING, "Error in checking connection, errno = %d", errno);
    }
```

The logic is as follows: 
  if (errno == EAGAIN || errno == EINTR)
   {
    retry it
   } 
 else{
  destroy_slot
 }

If socekt fd in PGconn is -1 and errno is EAGAIN .  The pooler will in deadloop. The problem is in 
pqSocketCheck(pqReadReady will call it). If  socekt fd is -1. pqSocketCheck did not set errno. So if old errno is EAGAIN. Pooler will in deadloop

Change code is as follows in pqSocketCheck.
        if (conn->sock < 0)
    {
        printfPQExpBuffer(&conn->errorMessage,
                          libpq_gettext("socket not open\n"));
        SOCK_ERRNO=EBADF;  
        return -1;
    }

I have fixed this bug. Later I will send patch to your. If any problem. Please let me know.

**Comment by koichi-szk** [comment]
Does it relate to pooler deadlock when DDL and DML are issued from more than one coordinator, or it happens always?

**Comment by xuegang** [comment]
In our enviroment, the probabilities of pooler deadloop(not deadlock) are very high.
You can recreate it with gdb:
  1.attach pool process 
  2add a breakpoint in "poll_result = pqReadReady((PGconn *) slot->conn);"
1. set socket fd in pgconn to -1;
   4.the probabilities of  errno=11 is very high(or you can set it 11 ).
   5.pooler is in deadloop

**Comment by galylee** [comment]
Does this issue already have patch?

**Comment by koichi-szk** [comment]
Yes, I believe so and it was committed.

---

Koichi Suzuki

2015-06-10 18:11 GMT+09:00 Galy Lee notifications@github.com:

**Comment by galylee** [comment]
Can we close this? Or any further improvment we need?

**Comment by koichi-szk** [comment]
See following pull requests.

https://github.com/postgres-x2/postgres-x2/pull/164
https://github.com/postgres-x2/postgres-x2/pull/225

Xuegang, please let me know if you have any more to commit.

Thank you;

---

Koichi Suzuki

2015-06-10 18:13 GMT+09:00 Koichi Suzuki koichi.dbms@gmail.com:

**Comment by koichi-szk** [comment]
Both two pull requests have been checked in.   Refer to each pull request log.

Closed.
