### ISSUE TITLE
We should move `GTM_ThreadRemove' to the front of MemoryContext cleanup in `GTM_threadCleanup'

### ISSUE THREAD

**Issue by DBInsight** [postgres-x2/postgres-x2#243]
We should move `GTM_ThreadRemove' to the front of MemoryContext cleanup in`GTM_threadCleanup', because `GTM_ThreadRemove' may report error that need`ErrorContext' which has been cleared since we call MemoryContext cleanup before `GTM_threadCleanup'.

thoughts?

**Comment by DBInsight** [comment]
or we should replace the elog(ERROR) in `GTM_ThreadRemove` with Assert.

thoughts?

**Comment by koichi-szk** [comment]
Agreed.   Could you provide a patch?

**Comment by koichi-szk** [comment]
Any update on this?

**Comment by DBInsight** [comment]
sorry taking so long, this is patch,

```
--- a/src/gtm/main/gtm_thread.c
+++ b/src/gtm/main/gtm_thread.c
@@ -119,11 +119,12 @@ GTM_ThreadRemove(GTM_ThreadInfo *thrinfo)
                        break;
        }

-       if (ii == GTMThreads->gt_array_size)
-               elog(ERROR, "Thread (%p) not found ", thrinfo);
+       if (ii < GTMThreads->gt_array_size)
+       {
+               GTMThreads->gt_threads[ii] = NULL;
+               GTMThreads->gt_thread_count--;
+       }

-       GTMThreads->gt_threads[ii] = NULL;
-       GTMThreads->gt_thread_count--;
        GTM_RWLockRelease(&GTMThreads->gt_lock);

        pfree(thrinfo);
```

**Comment by koichi-szk** [comment]
Are there any other safeguard that ii does not grow beyond GTMThreads->gt_sarray_size?

**Comment by DBInsight** [comment]
In theory, ii should not grow beyond GTMThreads->gt_sarray_size.

发件人: Koichi Suzuki [mailto:notifications@github.com]
发送时间: 2015年9月8日 16:23
收件人: postgres-x2/postgres-x2
抄送: Wangchuanting
主题: Re: [postgres-x2] We should move `GTM_ThreadRemove' to the front of MemoryContext cleanup in`GTM_threadCleanup' (#243)

Are there any other safeguard that ii does not grow beyond GTMThreads->gt_sarray_size?

**Comment by koichi-szk** [comment]
I reviewed the former lines of the function and ii does not grow beyond the array boundary.

On the other hand, as long as we have a chance to see the error message there, there's another problem where wrong thrinfo is passed to GTM_ThreadRemove.

In this case, only passed thrinfo is freed (by pfree), where there are no guarantee that such thrinfo is palloc'ed and in this case another problem will happen with pfree.

Any feedbacks?

**Comment by DBInsight** [comment]
Yes, maybe we should move pfree into the if statement too, thoughts?

发件人: Koichi Suzuki [mailto:notifications@github.com]
发送时间: 2015年9月8日 16:33
收件人: postgres-x2/postgres-x2
抄送: Wangchuanting
主题: Re: [postgres-x2] We should move `GTM_ThreadRemove' to the front of MemoryContext cleanup in`GTM_threadCleanup' (#243)

I reviewed the former lines of the function and ii does not grow beyond the array boundary.

On the other hand, as long as we have a chance to see the error message there, there's another problem where wrong thrinfo is passed to GTM_ThreadRemove.

In this case, only passed thrinfo is freed (by pfree), where there are no guarantee that such thrinfo is palloc'ed and in this case another problem will happen with pfree.

Any feedbacks?

**Comment by koichi-szk** [comment]
Okay, also it will be nice to pfree after lock release.   I will make this change and commit.

Thank you.

**Comment by koichi-szk** [comment]
Here's my version of the patch.   Hope it is okay.

```
diff --git a/src/gtm/main/gtm_thread.c b/src/gtm/main/gtm_thread.c
index 4612023..59fc7c9 100644
--- a/src/gtm/main/gtm_thread.c
+++ b/src/gtm/main/gtm_thread.c
@@ -116,17 +116,21 @@ GTM_ThreadRemove(GTM_ThreadInfo *thrinfo)
        for (ii = 0; ii < GTMThreads->gt_array_size; ii++)
        {
                if (GTMThreads->gt_threads[ii] == thrinfo)
+               {
+                       GTMThreads->gt_threads[ii] = NULL;
+                       GTMThreads->gt_thread_count--;
                        break;
+               }
        }

-       if (ii == GTMThreads->gt_array_size)
-               elog(ERROR, "Thread (%p) not found ", thrinfo);
-
-       GTMThreads->gt_threads[ii] = NULL;
-       GTMThreads->gt_thread_count--;
        GTM_RWLockRelease(&GTMThreads->gt_lock);

-       pfree(thrinfo);
+       /*
+        * It is dangerous to free invalid thrinfo, not found
+        * in GTMThreads.
+        */
+       if (ii < GTMThreads->gt_array_size)
+               pfree(thrinfo);

        return 0;
 }
```

**Comment by DBInsight** [comment]
It’s okay

发件人: Koichi Suzuki [mailto:notifications@github.com]
发送时间: 2015年9月8日 16:45
收件人: postgres-x2/postgres-x2
抄送: Wangchuanting
主题: Re: [postgres-x2] We should move `GTM_ThreadRemove' to the front of MemoryContext cleanup in`GTM_threadCleanup' (#243)

Here's my version of the patch. Hope it is okay.

diff --git a/src/gtm/main/gtm_thread.c b/src/gtm/main/gtm_thread.c

index 4612023..59fc7c9 100644

--- a/src/gtm/main/gtm_thread.c

+++ b/src/gtm/main/gtm_thread.c

@@ -116,17 +116,21 @@ GTM_ThreadRemove(GTM_ThreadInfo *thrinfo)

```
    for (ii = 0; ii < GTMThreads->gt_array_size; ii++)

    {

            if (GTMThreads->gt_threads[ii] == thrinfo)
```
- ```
            {
  ```
- ```
                    GTMThreads->gt_threads[ii] = NULL;
  ```
- ```
                    GTMThreads->gt_thread_count--;
  
                  break;
  ```
- ```
            }
  
  }
  ```
- ```
    if (ii == GTMThreads->gt_array_size)
  ```
- ```
            elog(ERROR, "Thread (%p) not found ", thrinfo);
  ```

## 
- ```
    GTMThreads->gt_threads[ii] = NULL;
  ```
- ```
    GTMThreads->gt_thread_count--;
  
  GTM_RWLockRelease(&GTMThreads->gt_lock);
  ```
- ```
    pfree(thrinfo);
  ```
- ```
    /*
  ```
- ```
     * It is dangerous to free invalid thrinfo, not found
  ```
- ```
     * in GTMThreads.
  ```
- ```
     */
  ```
- ```
    if (ii < GTMThreads->gt_array_size)
  ```
- ```
            pfree(thrinfo);
  
  
  
  return 0;
  ```
  
  }

—
Reply to this email directly or view it on GitHubhttps://github.com/postgres-x2/postgres-x2/issues/243#issuecomment-138481495.

**Comment by koichi-szk** [comment]
It has been committed to all the relevant branches:

master: ad633ce88d49cd69f39dd34ebd45adef2372abac
REL1_2_STABLE: e56bbd35c10215cf75a4c47e8fe2812d51a81d4e
REL1_1_STABLE: c246b2fae691f260919af5c370bd98af488778f3
