### ISSUE TITLE
help help help!!

### ISSUE THREAD

**Issue by caiyt** [postgres-x2/postgres-x2#251]
```
I encountered an issue when I operated with pgxl today. I hope someone can help me out.
There are 2 data nodes. I chose to store the data of table dwd.area_info distributed by replication. Somehow one of the nodes stores all the data of the table dwd.area_info, while the other one stores nothing. As a result, when I counted the rows of the table dwd.area_info, sometimes it returned 0, sometimes it returned correct result.
following is how I created table dwd.area_info:
```

drop table if exists dwd.area_info;
/_==============================================================_/
/\* Table: area_info                                             _/
/_==============================================================_/
create table dwd.area_info (
   /_area_id_/
   area_id              varchar(10)          not null,
   /_area_name_/
   area_name            varchar(50)          not null,
   /_parentarea_id_/
   parentarea_id        varchar(5)           not null,
   /_areatype_id_/
   areatype_id          int2                 not null,
   /_areastate_id_/
   areastate_id         int2                 not null,
   /_sortcode_/
   sortcode             int                  not null,
   /_bigarea_name_/
   bigarea_name         varchar(50)          null,
   /_province_name_/
   province_name        varchar(50)          not null,
   /_city_name_/
   city_name            varchar(50)          not null,
   /_county_name_/
   county_name          varchar(50)          not null,
   /_bigarea_id_/
   bigarea_id           varchar(10)          null,
   /_province_id_/
   province_id          varchar(10)          not null,
   /_city_id_/
   city_id              varchar(10)          not null,
   /_county_id*/
   county_id            varchar(10)          not null
)
tablespace tbsdwddata
distribute by replication;

alter table area_info
   add constraint pk_area_info primary key (area_id);
# 

Following is the steps inserting data：

truncate TABLE dwd.area_info;

insert into dwd.area_info
SELECT 
areaid,
areaname,
parentareaid,
areatype,
areastate,
sortcode,
f_getcityname(areaid,0) bigareaname,
f_getcityname(areaid,1) provname,
f_getcityname(areaid,2) cityname,
f_getcityname(areaid,3) countyname,
f_getcityid(areaid,0) bigareaid,
f_getcityid(areaid,1) provid,
f_getcityid(areaid,2) cityid,
f_getcityid(areaid,3) countyid
FROM ods.area_info_ful;

create or replace FUNCTION dim.f_getcityid(in_areaid varchar,in_areatype int) RETURNS VARCHAR AS $$
DECLARE 
    v_areainfo_row record;
    v_areainfo_row2 record;
    v_result VARCHAR(50);
    v_minus int;
    v_index int;
    v_parentareaid VARCHAR(20);
BEGIN
        -- get the hierarchy of current area.
        SELECT areaid,areaname,areatype,parentareaid 
            INTO v_areainfo_row
        FROM ods.area_info_ful a 
        WHERE areaid=in_areaid;

```
    IF v_areainfo_row.areatype < in_areatype THEN 
        v_result := '0';
    ELSEIF v_areainfo_row.areatype = in_areatype THEN
        v_result := v_areainfo_row.areaid;
    ELSE 
        v_minus := v_areainfo_row.areatype-in_areatype ;

        v_index := 0;
        v_parentareaid := v_areainfo_row.parentareaid;
        WHILE v_index < v_minus loop
            -- get higher level of the area
            SELECT areaid,areaname,areatype,parentareaid 
                INTO v_areainfo_row2
            FROM ods.area_info_ful a 
            WHERE areaid=v_parentareaid;
            v_parentareaid := v_areainfo_row2.parentareaid ;
            v_index := v_index+1;               
        END loop;
        -- return the final result
        v_result := v_areainfo_row2.areaid;                     
    END IF; 
    RETURN v_result;
```

END;
$$ LANGUAGE plpgsql;

CREATE or replace FUNCTION dim.f_getcityname (in_areaid VARCHAR,in_areatype INT) RETURNS VARCHAR AS $$
DECLARE 
    v_areainfo_row record;
    v_areainfo_row2 record;
    v_result VARCHAR(50);
    v_minus int;
    v_index int;
    v_parentareaid VARCHAR(20);
BEGIN
        -- get the hierarchy of current area.
        SELECT areaid,areaname,areatype,parentareaid 
            INTO v_areainfo_row 
        FROM ods.area_info_ful a 
        WHERE areaid=in_areaid;

```
    IF v_areainfo_row.areatype < in_areatype THEN 
        v_result := '-';
    ELSEIF v_areainfo_row.areatype = in_areatype THEN
        v_result := v_areainfo_row.areaname;
    ELSE 
        v_minus := v_areainfo_row.areatype-in_areatype ;

        v_index := 0;
        v_parentareaid := v_areainfo_row.parentareaid;
        WHILE v_index < v_minus loop
            -- get higher level of the area
            SELECT areaid,areaname,areatype,parentareaid 
                INTO v_areainfo_row2
            FROM ods.area_info_ful a 
            WHERE areaid=v_parentareaid;
            v_parentareaid := v_areainfo_row2.parentareaid ;
            v_index := v_index+1;                   
        END loop;
        -- return the final result
            v_result := v_areainfo_row2.areaname;                       
    END IF; 
    RETURN v_result;
```

END;
$$ LANGUAGE plpgsql;

f_getcityname，f_getcityid are two functions 

1、When I change the distribution method from replication to hash, everything goes well.
2、Also If I change the type of the function f_getcityname，f_getcityid from volatile to stable, the problem can be solved.

All in all, I think it might be a bug of pgxl. I hope someone can give me a further explanation. Thank you so much!

**Comment by koichi-szk** [comment]
Yes, it seems to be a bug.   Sorry I didn't respond for long.   I saw this forwarded to mail gmail account and found this is XL.   Sorry this is for X2.   If you need some more help, posting to XL mailing list will be better.    Your problem looks the same in both XL and X2 (they share most of the code).

Anyway, yes, it looks to be a bug.     You mentioned that changing the table into "REPLICATE BY HASH" resolves the problem.  I wonder that you cannot add PKAY after you careated the table as REPLICATE BY HASH.   Did you create the table as REPLICATED BY HASH?

Function handling for STABLE is similar to VOLATILE, in the sense that they are not pushed down to datanodes.   They are evaluated at the originating coordinator.

So I wonder if there's data inconsistencies to each replica of the tables.    Could you try to issue EXECUTE DIRECT ON (datanode) 'SELECT AREA_ID FROM DWD.AREA_INFO'; for each datanode?  I suspect there's some data inconsistencies among the datanodes.

Thank you very much;

**Comment by caiyt** [comment]
Thank you for your answer.

Not  "REPLICATE BY HASH"  is “Distribute by hash”

EXECUTE DIRECT ON (datanode) 'SELECT AREA_ID FROM DWD.AREA_INFO'; 
One node is all data
Another node has no data

**Comment by koichi-szk** [comment]
Yeah, I suspect INSERT ... SELECT ... was not planned correctly.

Could you try COPY TO and COPY FROM to setup the initial data of `dwd.area_info`?   This can be a workaround for this issue.

Thanks.
