### ISSUE TITLE
OID duplicate in system catalog

### ISSUE THREAD

**Issue by koichi-szk** [postgres-x2/postgres-x2#254]
We have following OID duplicate in the system catalog.   It is seen in all the stable branches, as well as in the master.   Duplicates are OIDs for builtin collector functions for aggregation.

```
[koichi@everest:catalog]$ ./duplicate_oids 
2964
2965
2966
2967
2968
2995
2996
[koichi@everest:catalog]$ 
```

This needs a prompt fix.

**Comment by koichi-szk** [comment]
Checked the duplicate and got the following results:

```
[koichi@everest:catalog]$ grep 2965 *
indexing.h:DECLARE_UNIQUE_INDEX(pg_db_role_setting_databaseid_rol_index, 2965, on pg_db_role_setting using btree(setdatabase oid_ops, setrole oid_ops));
indexing.h:#define DbRoleSettingDatidRolidIndexId   2965
pg_proc.h:DATA(insert OID = 2965 (  int8_avg_collect            PGNSP PGUID 12 1 0 0 0 f f f f t f i 2 0 1016 "1016 1016" _null_ _null_ _null_ _null_ int8_avg_collect _null_ _null_ _null_ ));
[koichi@everest:catalog]$ grep 2964 *
pg_db_role_setting.h:#define DbRoleSettingRelationId 2964
pg_db_role_setting.h:CATALOG(pg_db_role_setting,2964) BKI_SHARED_RELATION BKI_WITHOUT_OIDS
pg_proc.h:DATA(insert OID = 2964 (  numeric_avg_collect     PGNSP PGUID 12 1 0 0 0 f f f f t f i 2 0 1231 "1231 1231" _null_ _null_ _null_ _null_ numeric_avg_collect _null_ _null_ _null_ ));
[koichi@everest:catalog]$ grep 2966 *
pg_proc.h:DATA(insert OID = 2966 (  float8_collect          PGNSP PGUID 12 1 0 0 0 f f f f t f i 2 0 1022 "1022 1022" _null_ _null_ _null_ _null_ float8_collect _null_ _null_ _null_ ));
toasting.h:DECLARE_TOAST(pg_db_role_setting, 2966, 2967);
toasting.h:#define PgDbRoleSettingToastTable 2966
[koichi@everest:catalog]$ grep 2967 *
pg_proc.h:DATA(insert OID = 2967 (  interval_collect            PGNSP PGUID 12 1 0 0 0 f f f f t f i 2 0 1187 "1187 1187" _null_ _null_ _null_ _null_ interval_collect _null_ _null_ _null_ ));
toasting.h:DECLARE_TOAST(pg_db_role_setting, 2966, 2967);
toasting.h:#define PgDbRoleSettingToastIndex 2967
[koichi@everest:catalog]$ grep 2968 *
pg_amop.h:DATA(insert ( 2968  2950 2950 1 s 2974    403 0 ));
pg_amop.h:DATA(insert ( 2968  2950 2950 2 s 2976    403 0 ));
pg_amop.h:DATA(insert ( 2968  2950 2950 3 s 2972    403 0 ));
pg_amop.h:DATA(insert ( 2968  2950 2950 4 s 2977    403 0 ));
pg_amop.h:DATA(insert ( 2968  2950 2950 5 s 2975    403 0 ));
pg_amproc.h:DATA(insert (   2968   2950 2950 1 2960 ));
pg_opclass.h:DATA(insert (  403     uuid_ops            PGNSP PGUID 2968  2950 t 0 ));
pg_opfamily.h:DATA(insert OID = 2968 (  403     uuid_ops        PGNSP PGUID ));
pg_proc.h:DATA(insert OID = 2968 (  numeric_collect         PGNSP PGUID 12 1 0 0 0 f f f f t f i 2 0 1231 "1231 1231" _null_ _null_ _null_ _null_ numeric_collect _null_ _null_ _null_ ));
[koichi@everest:catalog]$ grep 2995 *
pg_largeobject_metadata.h:#define LargeObjectMetadataRelationId  2995
pg_largeobject_metadata.h:CATALOG(pg_largeobject_metadata,2995)
pg_proc.h:DATA(insert OID = 2995 (  float8_regr_collect     PGNSP PGUID 12 1 0 0 0 f f f f t f i 2 0 1022 "1022 1022" _null_ _null_ _null_ _null_ float8_regr_collect _null_ _null_ _null_ ));
[koichi@everest:catalog]$ grep 2996 *
indexing.h:DECLARE_UNIQUE_INDEX(pg_largeobject_metadata_oid_index, 2996, on pg_largeobject_metadata using btree(oid oid_ops));
indexing.h:#define LargeObjectMetadataOidIndexId    2996
pg_proc.h:DATA(insert OID = 2996 (  int8_sum_to_int8            PGNSP PGUID 12 1 0 0 0 f f f f f f i 2 0 20 "20 20" _null_ _null_ _null_ _null_ int8_sum_to_int8 _null_ _null_ _null_ ));
[koichi@everest:catalog]$ 
```

This shows the conflict with operator type 403, largeobject and toast internal builtin functions.

So this conflict may have caused the problem of toast and operator 403.  Largeobject was not impacted because XC does not support it and block relevant operations.

**Comment by koichi-szk** [comment]
Unused OID list is as follows (master):

```
[koichi@everest:catalog]$ unused_oids 
2 - 9
32
86 - 88
3177 - 3199
3205 - 3455
3457 - 3465
3475 - 3499
3546 - 3565
3567 - 3591
3779 - 3808
3846 - 3847
3920 - 3921
3931 - 3932
3935 - 3936
3939 - 3940
3968 - 3999
4033 - 9000
9004 - 9009
9016 - 9999
[koichi@everest:catalog]$ 
```

To avoid future conflict, we should assign XC-specific OIDs to 8001 to 9000.   Other OID may conflict too, for example, pgxc_class, pgxc_node, and pgxc_group catalog OIDs.

Problems:  the update may cause database binary incompatibilities.   So we need to decide how to implement this into existing major releases.

**Comment by koichi-szk** [comment]
Pgxc_\* catalog oids have already been assigned at 9000- range as follows:

```
[koichi@everest:catalog]$ grep 9001 *
pgxc_class.h:#define PgxcClassRelationId  9001
pgxc_class.h:CATALOG(pgxc_class,9001) BKI_WITHOUT_OIDS
[koichi@everest:catalog]$ grep 9002 *
indexing.h:DECLARE_UNIQUE_INDEX(pgxc_class_pcrelid_index, 9002, on pgxc_class using btree(pcrelid oid_ops));
indexing.h:#define PgxcClassPgxcRelIdIndexId    9002
[koichi@everest:catalog]$ grep 9003 *
indexing.h:DECLARE_UNIQUE_INDEX(pgxc_node_id_index, 9003, on pgxc_node using btree(node_id int4_ops));
indexing.h:#define PgxcNodeNodeIdIndexId    9003
[koichi@everest:catalog]$ grep 9004 *
[koichi@everest:catalog]$ grep 9010 *
indexing.h:DECLARE_UNIQUE_INDEX(pgxc_node_oid_index, 9010, on pgxc_node using btree(oid oid_ops));
indexing.h:#define PgxcNodeOidIndexId           9010
[koichi@everest:catalog]$ grep 9011 *
indexing.h:DECLARE_UNIQUE_INDEX(pgxc_node_name_index, 9011, on pgxc_node using btree(node_name name_ops));
indexing.h:#define PgxcNodeNodeNameIndexId  9011
[koichi@everest:catalog]$ grep 9012 *
indexing.h:DECLARE_UNIQUE_INDEX(pgxc_group_name_index, 9012, on pgxc_group using btree(group_name name_ops));
indexing.h:#define PgxcGroupGroupNameIndexId    9012
[koichi@everest:catalog]$ grep 9013 *
indexing.h:DECLARE_UNIQUE_INDEX(pgxc_group_oid, 9013, on pgxc_group using btree(oid oid_ops));
indexing.h:#define PgxcGroupOidIndexId          9013
[koichi@everest:catalog]$ grep 9014 *
pgxc_group.h:#define PgxcGroupRelationId  9014
pgxc_group.h:CATALOG(pgxc_group,9014) BKI_SHARED_RELATION
[koichi@everest:catalog]$ grep 9015 *
pgxc_node.h:#define PgxcNodeRelationId  9015
pgxc_node.h:CATALOG(pgxc_node,9015) BKI_SHARED_RELATION
[koichi@everest:catalog]$
```

**Comment by DBInsight** [comment]
Is this a problem?  oid in different table can duplicate,

**Comment by koichi-szk** [comment]
Problem is OIDs in the catalog.   If they duplicate, different system
object may be identified as the same one, which may cause very serious
problem.   In our case, same OID was assigned to collector functions of
builtin aggregate and toast handler.    You may find some toast-related
problem report.   So sometimes it's a serious problem.

Latest PG makefile included a check for this duplicate.

Regards;

---

Koichi Suzuki

2015-06-30 12:16 GMT+09:00 DBInsight notifications@github.com:

**Comment by wurenny** [comment]
so what acctually problem, for example ? our product cluster has run nearly half a year, and we often use builtin collect functions
postgres=# select oid,relname from pg_class where relname like 'pgxc%' order by 1;
  oid  |         relname  
-------+--------------------------
  9001 | pgxc_class
  9002 | pgxc_class_pcrelid_index
  9003 | pgxc_node_id_index
  9010 | pgxc_node_oid_index
  9011 | pgxc_node_name_index
  9012 | pgxc_group_name_index
  9013 | pgxc_group_oid
  9014 | pgxc_group
  9015 | pgxc_node
 12630 | pgxc_prepared_xacts
(10 rows)

**Comment by koichi-szk** [comment]
OID for pgxc_xxx catalog has not problem.   Problem is oid assigned for `int8_avg_collect()`, `numeric_avg_collect()`, `float8_collect()`, `interval_collect()`, `numeric_collect()`, `float8_regr_collect()`, and `int8_sum_to_int8()`.

You can see this by issuing `./duplicate_oids` at `src/include/catalog`.

**Comment by wurenny** [comment]
if only oid problem, is there any way to avoid reinstall entire cluster use pg_dumpall ? for example supplying a upgrade script.  i'm afraid it is unacceptable to stop an product cluster and reinstall it.
and i want to know how can i triggger the problem by manual invoke these builtin functions ?

**Comment by Jasonysli** [comment]
Can we assign new OID to these system functions to slove the issue?

**Comment by koichi-szk** [comment]
This is what we meet when we upgrade PostgreSQL to major upgrade.   I
understand it is not convenient but XC inherit this from PG.   PG now has
pg-upgrade to upgrade internal catalog to incompatible version.   Because
it has to deal with internal catalog structure which is not directly
visible to application, we need to enhance pg-upgrade to work with XC.

---

Koichi Suzuki

2015-06-30 15:33 GMT+09:00 Renny notifications@github.com:

**Comment by koichi-szk** [comment]
Yes, this is the fix and is not hard to do.   Because this makes database
itself incompatible, I'm asking what is the best way to release.

---

Koichi Suzuki

2015-06-30 15:46 GMT+09:00 Jasonysli notifications@github.com:

**Comment by koichi-szk** [comment]
Could be related to the issue #165.

**Comment by koichi-szk** [comment]
Committed to mester, REL1_2_STABLE and REL1_1_STABLE.
