### ISSUE TITLE
too much LOG:  xid was less than ShmemVariableCache->nextXid

### ISSUE THREAD

**Issue by wurenny** [postgres-x2/postgres-x2#259]
i run pgbench use the lastest branch of REL_1_2_STABLE, i found too much these log records on coordinator:
LOG:  xid (2969482) was less than ShmemVariableCache->nextXid (2969484), IS_PGXC_COORDINATOR:1, IS_PGXC_DATANODE:0, REMOTE_CONN_TYPE:0, regen now
STATEMENT:  SELECT abalance FROM pgbench_accounts WHERE aid = 740761;
LOG:  xid (2969578) was less than ShmemVariableCache->nextXid (2969580), IS_PGXC_COORDINATOR:1, IS_PGXC_DATANODE:0, REMOTE_CONN_TYPE:0, regen now
STATEMENT:  SELECT abalance FROM pgbench_accounts WHERE aid = 1379227;
LOG:  xid (2969588) was less than ShmemVariableCache->nextXid (2969590), IS_PGXC_COORDINATOR:1, IS_PGXC_DATANODE:0, REMOTE_CONN_TYPE:0, regen now
STATEMENT:  SELECT abalance FROM pgbench_accounts WHERE aid = 634828;
LOG:  xid (2969595) was less than ShmemVariableCache->nextXid (2969597), IS_PGXC_COORDINATOR:1, IS_PGXC_DATANODE:0, REMOTE_CONN_TYPE:0, regen now
STATEMENT:  SELECT abalance FROM pgbench_accounts WHERE aid = 791938;

and on datanode:
xid (11353) does not follow ShmemVariableCache->nextXid (11355)
xid (11517) does not follow ShmemVariableCache->nextXid (11519)
xid (11585) does not follow ShmemVariableCache->nextXid (11587)
xid (11657) does not follow ShmemVariableCache->nextXid (11659)
xid (19750) does not follow ShmemVariableCache->nextXid (19755)
xid (19824) does not follow ShmemVariableCache->nextXid (19826)
xid (19897) does not follow ShmemVariableCache->nextXid (19899)
xid (20523) does not follow ShmemVariableCache->nextXid (20525)
xid (20528) does not follow ShmemVariableCache->nextXid (20533)

whether there are some harmful effect to the cluster ?

**Comment by Jasonysli** [comment]
This is just a log,  code will automaticly reget a xid to ensure all xid are got in order.

**Comment by koichi-szk** [comment]
Year, this log is printed when older GXID comes from a coordinator to a datanode.   This happens occasionally and this message has no significance.    Should we lower the priority of this message from LOG to NOTICE?

**Comment by wurenny** [comment]
it happened 100% at hign concurrency when i run pgbench, maybe INFO is better.

**Comment by koichi-szk** [comment]
Committed to the master as 45bb2594d39703180bec14b060d2cc7b3ce42b77.   This has been cherry-picked to REL1_2_STABLE and REL1_1_STABLE.

**Comment by wurenny** [comment]
i just test it, this log was gone in datanode, but still was printed in coordinator node, if it need to modify at line 163 in varsup.c ?

/\* It is a serious issue when xid fall back, so here we write a message to record this */
                    ereport(LOG,
                       (errmsg("xid (%d) was less than ShmemVariableCache->nextXid (%d), IS_PGXC_COORDINATOR:%d, IS_PGXC_DATANODE:%d, REMOTE_CONN_TYPE:%d, regen now",
                           xid, ShmemVariableCache->nextXid, IS_PGXC_COORDINATOR, IS_PGXC_DATANODE, REMOTE_CONN_TYPE)));

**Comment by koichi-szk** [comment]
I see, NOTIFY was not a good choice.  Debug1 could be a choice.    Let me
make another choice.

---

Koichi Suzuki
2015/07/07 15:30 "Renny" notifications@github.com:

**Comment by wurenny** [comment]
yes, that's very right, because LOG level would be printed in log file not clien message, but NOTICE level would be printed in client message not log file, so DEBUG1 is the best.
and i just run pgbench with modifing to DEBUG1 level, it seemed TPS got increased a little

**Comment by koichi-szk** [comment]
How about INFO?

---

Koichi Suzuki

2015-07-07 16:08 GMT+09:00 Renny notifications@github.com:

**Comment by wurenny** [comment]
INFO is similar to NOTICE, printed in client message too, i have tried it.

**Comment by koichi-szk** [comment]
Thanks.  Let me change it to DEBUG1.

---

Koichi Suzuki

2015-07-07 16:41 GMT+09:00 Renny notifications@github.com:

**Comment by wurenny** [comment]
sorry, i mean coordinator should turn to DEBUG1 as well:

/\* It is a serious issue when xid fall back, so here we write a message to record this */
                    ereport(DEBUG1,
                       (errmsg("xid (%d) was less than ShmemVariableCache->nextXid (%d), IS_PGXC_COORDINATOR:%d, IS_PGXC_DATANODE:%d, REMOTE_CONN_TYPE:%d, regen now",
                           xid, ShmemVariableCache->nextXid, IS_PGXC_COORDINATOR, IS_PGXC_DATANODE, REMOTE_CONN_TYPE)));

Thanks.

**Comment by koichi-szk** [comment]
In the datanode, order of received GXID depends upon the order of incoming transactions from coordinators.   So it is very common to receiver less value of GXID.

In the case of coordinators, it is supposed to have GXID value in order from GTM and it is serious if smaller GXID comes later.

I don't think this is a good idea to change this message level to DEBUG1.

Regards;

**Comment by wurenny** [comment]
However it indeed happened 100% on coordinator at hign concurrency when i run pgbench test, and i suspect this effect  TPS performance, maybe the implementation logic can be improved.

LOG: xid (4956182) was less than ShmemVariableCache->nextXid (4956205), IS_PGXC_COORDINATOR:1, IS_PGXC_DATANODE:0, REMOTE_CONN_TYPE:0, regen now
STATEMENT: SELECT abalance FROM pgbench_accounts WHERE aid = 450077;
LOG: xid (4956183) was less than ShmemVariableCache->nextXid (4956205), IS_PGXC_COORDINATOR:1, IS_PGXC_DATANODE:0, REMOTE_CONN_TYPE:0, regen now
STATEMENT: SELECT abalance FROM pgbench_accounts WHERE aid = 49623;

**Comment by wurenny** [comment]
i mean it happend 100% on coordinator at hign concurrency:
LOG:  xid (4956182) was less than ShmemVariableCache->nextXid (4956205), IS_PGXC_COORDINATOR:1, IS_PGXC_DATANODE:0, REMOTE_CONN_TYPE:0, regen now
STATEMENT:  SELECT abalance FROM pgbench_accounts WHERE aid = 450077;
LOG:  xid (4956183) was less than ShmemVariableCache->nextXid (4956205), IS_PGXC_COORDINATOR:1, IS_PGXC_DATANODE:0, REMOTE_CONN_TYPE:0, regen now
STATEMENT:  SELECT abalance FROM pgbench_accounts WHERE aid = 49623;

**Comment by koichi-szk** [comment]
Hmm,,, Yes, it could happen depending on the scheduler behavior and the order of each process kicked, especially in high workload.   Because pgbench runs at full workload, it may happen very frequently.   And, apparently, it is not the error in XC.

Okay, let me change the message level to DEBUG1, as long as it is not a fault and is not good to have it at the terminal/server log as a default.

Will be closed after the patch is pushed.

Thanks.

**Comment by koichi-szk** [comment]
The patch was committed to master (1659fe305aed2b7993c557cf5f26e8d33b60cb89), REL1_2_STABLE and REL1_1_STABLE.
