### ISSUE TITLE
pg_x2 produces warning massage such as: LOG:  failed to find proc 0x7fe6235db260 in ProcArray

### ISSUE THREAD

**Issue by scarbrofair** [postgres-x2/postgres-x2#273]
I install a pg_x2 cluster and run some sql to verify some tickets of 1.2.3. 
However, I find many warning message in the log file of datanodes and coordinators. The warning messages are as following:

LOG:  failed to find proc 0x7fe6235db260 in ProcArray

I investigate the pg 9.3 and 9.4, find no such issue. I find this message is produced by the function named ProcArrayRemove() in src/backend/storage/ipc/procarray.c. 
I use gcc 4.8.3 and O2 option to compile pg_x2 and install it. 
I think this issue is introduced by pg_xc in the structure of ProcArrayStruct. pg_xc adds a new field named  pgAVproxnos, but no other places access it. 
I write a simple c program to simulate this issue. (I don't know how to update this C program to github) 
There are some ways to fix this issue:
    1, remove this unused codes
    2,  rewrite the VARIABLE LENGTH ARRAY, from array[1] to array[0]
    3, report this bug to gcc and see if gcc can fix this case

**Comment by scarbrofair** [comment]
Following is the C program I used to simulate this case:

```
#include  <stdio.h>
#define PROCARRAY_MAXPROCS 10
typedef size_t Size;
#define offsetof(type, field)   ((long) &((type *)0)->field)

typedef struct ProcArrayStruct
{
    int         numProcs;       /* number of valid procs entries */
    int         maxProcs;       /* allocated size of procs array */
    int         pgprocnos[1];   /* VARIABLE LENGTH ARRAY */
#ifdef PGXC
    int         pgAVproxnos[1];
#endif
} ProcArrayStruct;
static ProcArrayStruct *procArray;

static Size add_size(Size s1, Size s2)
{
    Size        result;
    result = s1 + s2;
    return result;
}

static Size mul_size(Size s1, Size s2)
{
    Size        result;
    if (s1 == 0 || s2 == 0)
        return 0;
    result = s1 * s2;
    return result;
}
static void CreateSharedProcArray(void)
{
    Size fix_length = offsetof(ProcArrayStruct, pgprocnos);
    Size var_length = mul_size(sizeof(int), PROCARRAY_MAXPROCS);
    Size sum_length = add_size(fix_length,var_length);
    procArray = (ProcArrayStruct *) calloc(sum_length, sizeof(char));

    procArray->numProcs = 0;
    procArray->maxProcs = PROCARRAY_MAXPROCS;
    return ;
}

static void ProcArrayAdd(int id)
{
    ProcArrayStruct *arrayP = procArray;
    int         index;
    if (arrayP->numProcs >= arrayP->maxProcs)
    {
        printf("too many data to insert\n");
        return ;
    }
    for (index = 0; index < arrayP->numProcs; index++)
    {
        if ((arrayP->pgprocnos[index] == -1) || (arrayP->pgprocnos[index] > id))
            break;
    }
    memmove(&arrayP->pgprocnos[index + 1], &arrayP->pgprocnos[index],
            (arrayP->numProcs - index) * sizeof(int));
    arrayP->pgprocnos[index] = id;
    arrayP->numProcs++;
    for (index = 0; index < arrayP->numProcs; index++)
    {
        printf("index %d and  id %d numProcs is %d\n", index, arrayP->pgprocnos[index], arrayP->numProcs);
    }
    return ;
}

static void ProcArrayRemove(int id)
{
    ProcArrayStruct *arrayP = procArray;
    int         index;
    printf("Before remove proc id %d\n", id);
    for (index = 0; index < arrayP->numProcs; index++)
    {
        printf("index %d and  id %d\n", index, arrayP->pgprocnos[index]);
    }
    for (index = 0; index < arrayP->numProcs; index++)
    {
        if (arrayP->pgprocnos[index] == id)
        {
            /* Keep the PGPROC array sorted. See notes above */
            memmove(&arrayP->pgprocnos[index], &arrayP->pgprocnos[index + 1],
                    (arrayP->numProcs - index - 1) * sizeof(int));
            arrayP->pgprocnos[arrayP->numProcs - 1] = -1;       /* for debugging */
            arrayP->numProcs--;
        }
    }
    printf("After remove proc id %d\n", id);
    for (index = 0; index < arrayP->numProcs; index++)
    {
        printf("index %d and  id %d\n", index, arrayP->pgprocnos[index]);
    }
    return;
}

int main(int argc, char** argv)
{
    CreateSharedProcArray();
    ProcArrayAdd(103);
    ProcArrayAdd(99);
    ProcArrayAdd(102);
    ProcArrayRemove(103);
    ProcArrayRemove(102);
    ProcArrayRemove(99);
}
```

On CentOS 7.0 with GCC 4.8.3, I use -DPGXC and O2/O1/O3 option to compile this program and run it to simulate this case.

**Comment by koichi-szk** [comment]
I reviewed how additional members, `pgprocnos`, is used and found it is never used!

Maybe this is not needed.   I'm commented this number out.   Through regression test, there seems no problem with it.  Could you comment this member out and see what you have in your environment?   If the result is as you expect, I will push this to the repo.

Thank you;

**Comment by scarbrofair** [comment]
Yes, I remove it and no warning Now. I think we need to remove it

**Comment by scarbrofair** [comment]
And on the other side, I think it lucky for us to find this bug when it just produces warning message, because this bug will make coordinator/datanode only add proc to ProcArray but fail to remove proc from ProcArray. So after some time, the ProcArray will be full and cannot accept new proc and produce a error message of "sorry, too many clients already", which means coordinator/datanode will not accept new connection any more.

**Comment by koichi-szk** [comment]
Thanks a lot for finding this bug.   It was committed to all the relevant branches.

Master: 5c0c4576faed4085cb91b1a211600c7776021c77
REL1_2_STABLE: 6f8bdf5b300bd207ff738d6ec3f782bf71ef7fc6
REL1_1_STABLE: 7e4da10853ca913eea82af8abdeb3a132f530d52

**Comment by koichi-szk** [comment]
Duplicate to #72.
