### ISSUE TITLE
when i test the performance, I found high disk I/O in gtm.

### ISSUE THREAD

**Issue by xuegang** [postgres-x2/postgres-x2#282]
Further analysis, I found that every call "select nextval('testseq')", gtm will write data into gtm.control. 

Recreate steps:
    1. create table test1(id serial,name text) distribute by replication;

vim gtm.control
   postgres.public.test1_id_seq\00 2001    1       1       1       9223372036854775806     f       f       1

2.insert into test1(name) values ('a');
3.insert into test1(name) values ('a');

vim gtm.contol
    postgres.public.test1_id_seq\00 2002    1       1       1       9223372036854775807     f       t       1

Now I have fix this bug,  Later I will send this patch to you. If any problem. Please let me know.

Now I have do some test as follows:

```
1.insert 2000 recoreds "insert into test2(name) select generate_series(1,1000);".  Gtm will write   
        sequence into gtm.contol
2.kill -9 gtm
3.kill -15 gtm
```

For me.All test is ok.

**Comment by koichi-szk** [comment]
gtm writes and synch-es its restart point to gtm.control file for every 4000 GXID or sequence update.   Also, register.node will be updated for each connection from gtm_proxy or client (if gtm_proxy is not configured).

I didn't think these I/O is not significant.

**Comment by koichi-szk** [comment]
The fix has been committed to relevant branches:

master: 72494b5711b10a79e53e5a8edfc94a12d46e49c2
REL1_2_STABLE: 34e484665fa2285515dc0a007db4e1adf0b2d0cb
REL1_1_STABLE: f8442cb990c4bb0a9dac6fd7ff84dd26a75dfad9
