### ISSUE TITLE
fix two bug about sequence 

### ISSUE THREAD

**Issue by xuegang** [postgres-x2/postgres-x2#283]
Bug 1
  Recreate step:
      1.create sequence test_seq increment by -1
      2.vim gtm.control
            postgres.public.test_seq\00     -9223372036854775807    -1      -1   -9223372036854775807  
                -1      f       f       1

```
  This bug is that last_value of sequnence " -9223372036854775807" is wrong. The right value is 
    -2001.
```

second bug is as follows:
   1.create sequence test_seq increment by -1
   2.call twice "select nextval('test_seq ')" 
   3.kill -9 gtm
1. restart gtm
   5.select nextval('test_seq ');
   6.you will get -1

you will found that nextval got the wrong value, the right value is -2001

Now I have fix these two bugs. Later I will commit patch to you. if any problem. Please let me know.

**Comment by koichi-szk** [comment]
Okay, please submit pull requests.

**Comment by koichi-szk** [comment]
The fix was committed to relevant branches,

master: 64c43fc09492a5d2d29d92aa98ccd12006ed154c
REL1_2_STABLE: fdbbd077c4982c470fe78eac4db912c028db5fc1
REL1_1_STABLE: 8d590b5ed227b5b05efadbe51c76180bc5a4149b
