### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by dimv36** [postgres-x2/postgres-x2#289]
Hello, guys. 

I use Postgres-XC 1.2.1 stable. During the compilation we have some warnings:
warning: implicit declaration of function 'heap_modify_tuple' [-Wimplicit-function-declaration]
warning: assignment makes pointer from integer without a cast [enabled by default]

in pgxc_class.c. 

It may cause a segfault error in some cases.

So, those warnings can be resolved by adding to pgxc_class.c include directive 
# include access/htup_details.h"

Warnings about CATALOG macros can be resolved by adding
# include "catalog/genbki.h"

in pgxc_*.h 

Thank you.

**Comment by koichi-szk** [comment]
Thank you very much for pointing out.

Okay, this will be committed to all the relevant branches in as early as
possible.

Best;

---

Koichi Suzuki
https://www.linkedin.com/in/koichidbms

2015-09-03 16:52 GMT+09:00 Dmitry Voronin notifications@github.com:

**Comment by koichi-szk** [comment]
The issue has been fixed for 1.2.2 purpose.   Now closing.
