### ISSUE TITLE
Question: authorization in Postgres-XC

### ISSUE THREAD

**Issue by dimv36** [postgres-x2/postgres-x2#292]
Guys, can you tell me, how authorization work?
Postgres-XC after start works under postgres-xc user and after user's connection change role by SET SESSION AUTHORIZATION?

**Comment by koichi-szk** [comment]
Pooler takes care of authorization and SET command for each pooled connection between the nodes.  When pooler assigns connection to a coordinator, it tests current coordinator's set command status with pooled one and change pooled connections's Set command status before it is assigned.

**Comment by dimv36** [comment]
So, authorization are finished via SET SESSION AUTHORIZATION, right?

**Comment by koichi-szk** [comment]
Sorry, I'm not sure.   Pooler has information of each pooled connection's
authorization and assigns one of them with proper authorization and target
database.   Maybe pooler need new connection with different user/database
and there could be some room for improvement.

---

Koichi Suzuki
https://www.linkedin.com/in/koichidbms

2015-09-07 15:06 GMT+09:00 Dmitry Voronin notifications@github.com:

**Comment by dimv36** [comment]
Ok, thank you.
