### ISSUE TITLE
2 questions about the behavior of gtm proxy main thread when meet too many connections

### ISSUE THREAD

**Issue by scarbrofair** [postgres-x2/postgres-x2#306]
As we know, when there is a new connection coming, the main thread will check whether one specified work thread has free socket descriptor, if true, all is OK. However, if not, the function named GTMProxy_ThreadAddConnection will report an error and the whole program will abort ( for detail you can check errstart() and elog_finish(), please note PG_exception_stack is NULL). I meet the case when pressure test with more thousands backends. 
So my first question is: why the main thread need to exit under this situation?  Since there is 1024 connections to the backends, the abortion will kill all this transactions serviced by these connections. May be the main thread can just drop this new connection rather than kill the whole proxy.
Second question: when picking the work thread, the main thread just check the thread specified by GTMProxyThreads->gt_next_worker,  if this work thread is not available, GTMProxy_ThreadAddConnection will report an error. Why not to check all of the work threads to find the work thread available?

**Comment by yazun** [comment]
I made a patch for XL that should be applicable to X2 as well to use poll
instead of select() which has hard limit of 1024 sockets.
In fact all selects()/polls() should be refactored to use epolls().
Cheers

**Comment by scarbrofair** [comment]
Agree with part of your words : first, the main thread will just listen a few socket, select is enough; and second, the main thread need to drop new connections if worker thread is not available.
On the other side, I try to use epoll to replace poll in worker thread, for higher performance. I'm trying to refactor gtm proxy. 
These questions is a part of my patch.

**Comment by koichi-szk** [comment]
https://github.com/postgres-x2/postgres-x2/pull/307 fixed the issue.

**Comment by yazun** [comment]
Was not select performed by the kernel on all opened descriptors by the
process, so even if you listen on 10 but opened 1000 elsewhere kernel would
still have to scan 1010 in the worst case?

**Comment by scarbrofair** [comment]
OK, got it, I investigate the implementation in kernel. Thanks
