### ISSUE TITLE
does datanode need to communicate with gtm or gtm proxy ?

### ISSUE THREAD

**Issue by wurenny** [postgres-x2/postgres-x2#312]
Accidently, our pgx2 product cluster had some trouble after we had finished the pgx2's metting on 22th NOV, i found one node of cluster's gtm proxy stoped with unknown reason and this node can't provide database service for applications, but coodinator and datanode's processes looked like normal, after a while, my manager switch all applications connection-string to another node's coordinator, it accually works ! 

it seems the datanode is irrelevant with gtm or gtm proxy, but as we know, datanode need gtm or gtm proxy when it is starting

so i wonder if the datanode need to communicate with gtm or gtm proxy after it started, and if need, what it do in the communication ?

and, Scarbrofair told me he has pull a patch for this problem and planning in 1.2.2 milestone, so i also wonder when the V1.2.2 will release.

**Comment by koichi-szk** [comment]
Datanode needs connection to gtm when gxid/snapshot is not supplied by the coordinator and when it needs snapshot synchronization.

At least we have two cases when datanode needs gxid/snapshot from gtm:

1) autovacuum
2) maintenance work with xc_maintenance_mode on.

Also, to resolve update inconsistency, updating datanode backend synchronizes snapshot broadcast with local commit by obtaining snapshot when backend commit status is inconsistent with the snapshot.   It is essential to resolve inconsistent update.

I don't think it's a good idea to exclude gtm connection from datanodes.

Thanks.

**Comment by wurenny** [comment]
So in a normal transaction process: datanode obtains snapshot from coordinator, and coordinator obtains snapshot from gtm ?

**Comment by koichi-szk** [comment]
Yes, this is how all the local transactions from the root coordinator
transaction shares GXID and snapshot.

---

Koichi Suzuki
https://www.linkedin.com/in/koichidbms

2015-11-25 17:29 GMT-08:00 Renny notifications@github.com:
