### ISSUE TITLE
Insert is quite slow on table distribute by hash

### ISSUE THREAD

**Issue by d9liang** [postgres-x2/postgres-x2#338]
Not sure if it's expected or a performance issue, but it takes almost one hour to insert 10m rows:

create table t4 (id int, cat int, info text, amt int) distribute by hash(id);
insert into t4 select generate_series(1,10000000),round(random()*5),'dd',round(random()*999);

The cluster has one GTM, 4 coordinators, and 4 data nodes on AWS

**Comment by d9liang** [comment]
@koichi-szk we're evaluating PGX2 for an on-going project. It'd be great if you can take a look into this and get back to me soon.

**Comment by d9liang** [comment]
I figured out another way to handle the problem by creating an external file then bulk loading
(COPY) it. It's running in less than 10 seconds now.

**Comment by d9liang** [comment]
Problem fixed, now closing.

**Comment by koichi-szk** [comment]
Sorry for the late response.   COPY sounds nice.   Another way is to divide
your insert workload and put it from different coordinator in parallel.   I
hope this works well too.

---
Koichi Suzuki
https://www.linkedin.com/in/koichidbms


2017-02-23 3:48 GMT+09:00 d9liang <notifications@github.com>:
