### ISSUE TITLE
Some statment stucks with EXECUTE DIRECT

### ISSUE THREAD

**Issue by koichi-szk** [postgres-x2/postgres-x2#54]
This was submitted by Koichi Suzuki, 2013-06-06.

See [sourceforge bug tracker](http://sourceforge.net/p/postgres-xc/bugs/427/) for details.

The following satement stucks. It used to work at 1.0.x.
Running this with direct connection to a datanode works correctly.

```
EXECUTE DIRECT ON (someDataNode) $$
SELECT
count(*)
FROM
(SELECT * FROM pg_locks l LEFT JOIN
(SELECT * FROM pg_stat_activity) s ON l.database = s.datid) a
$$
```

**Comment by scarbrofair** [comment]
Suggest close this issue, it works with latest code.

```
[pgsql@localhost bin]$ ./psql -d postgres -p15434
psql (PGXC 1.3devel, based on PG 9.4beta1)
Type "help" for help.

postgres=# EXECUTE DIRECT ON (dn1) $$  SELECT count(*) FROM (pg_locks l LEFT JOIN pg_stat_activity s ON (l.database = s.datid)) a $$;
 count 
-------
     9
(1 row)
```

And it is interesting to get a different result if we run this SQL on the datanode named dn1：

```
[pgsql@localhost bin]$ ./psql -d postgres -p15432
psql (PGXC 1.3devel, based on PG 9.4beta1)
Type "help" for help.

postgres=# SELECT count(*) FROM (pg_locks LEFT JOIN pg_stat_activity  ON (database = datid ) ) as a ;
 count 
-------
    12
(1 row)
```

However, this is not a bug. Since the results depends on the activity of datanode named dn1 when run this SQL.

**Comment by koichi-szk** [comment]
Okay, please reopen this when you have similar issue.
