### ISSUE TITLE
Production Platform Migration Error

### ISSUE THREAD

**Issue by koichi-szk** [postgres-x2/postgres-x2#72]
Submitted by Bill West, 2013-10-25.   See [sourceforge bug tracker](https://sourceforge.net/p/postgres-xc/bugs/460/) for details.

I have created an instance of postgres-xc on my production platform. I am getting errors that I did not see in development. The error message reads "LOG: failed to find proc 0x2b3412852dc0 in ProcArray". It fires off every minute or so. The database works to a point but seems unstable. It has trouble recognizing the number of active connections. I set it up to accept the default 100 connections but at best it will only accept 5 and gradually degrades until it will only accept 1. If I restart the service it improves but quickly degrades again. Has anybody experienced this type of error on installation before? The OS is GNU/Linux 64 Bit.

Thanks,
Bill West

**Comment by koichi-szk** [comment]
Need reproduction environment.

**Comment by scarbrofair** [comment]
I think it duplicated with issue 273

**Comment by koichi-szk** [comment]
Thanks a lot for pointing out.   Yes it is.   I will add "duplicate" label both to #273 and this and close this.
