### ISSUE TITLE
pg_dumpall: ERROR:  cannot execute nextval() in a read-only transaction

### ISSUE THREAD

**Issue by wurenny** [postgres-x2/postgres-x2#85]
i got a error when i backup  all databases use pg_dumpall, as steps:
# cat /etc/oracle-release

Oracle Linux Server release 6.6

postgres=# select pgxc_version();
pgxc_version
Postgres-XC on x86_64-unknown-linux-gnu, based on PostgreSQL 9.3.2, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11), 64-bit
(1 row)
postgres=# create table t(a serial);
LOG:  statement: create table t(a serial);
CREATE TABLE
postgres=# \q

[pgxc@masget3313 ~]$ pg_dumpall -f dumpall.bkp
pg_dump: [archiver (db)] query failed: ERROR:  cannot execute nextval() in a read-only transaction
pg_dump: [archiver (db)] query was: SELECT pg_catalog.nextval('t_a_seq');

pg_dumpall: pg_dump failed on database "postgres", exiting
------------------------------------------seperated line---------------------------------------

i found a patch with pg_dump for backup only one database on sourceforge: 
http://sourceforge.net/p/postgres-xc/mailman/postgres-xc-general/thread/5A050E14-AFE7-4673-A37A-6D9719ACC791@intellilink.co.jp
## patch content:

diff --git a/src/bin/pg_dump/pg_dump.c b/src/bin/pg_dump/pg_dump.c
index 1c6a535..7ff0a55 100644
--- a/src/bin/pg_dump/pg_dump.c
+++ b/src/bin/pg_dump/pg_dump.c
@@ -1013,9 +1013,15 @@ setup_connection(Archive *AH, const char *dumpencoding, char *use_role)
    if (AH->remoteVersion >= 90100)
    {
        if (serializable_deferrable)
+#ifdef PGXC
-           ExecuteSqlStatement(AH,
-                               "SET TRANSACTION ISOLATION LEVEL "
-                               "SERIALIZABLE, DEFERRABLE");
  +#else
          ExecuteSqlStatement(AH,
                              "SET TRANSACTION ISOLATION LEVEL "
                              "SERIALIZABLE, READ ONLY, DEFERRABLE");
  +#endif
      else
          ExecuteSqlStatement(AH,
                              "SET TRANSACTION ISOLATION LEVEL "
  @@ -1024,9 +1030,15 @@ setup_connection(Archive _AH, const char *dumpencoding, char *use_role)
  else if (AH->remoteVersion >= 70400)
  {
      /_ note: comma was not accepted in SET TRANSACTION before 8.0 */
  +#ifdef PGXC
-       ExecuteSqlStatement(AH,
-                           "SET TRANSACTION ISOLATION LEVEL "
-                           "SERIALIZABLE");
  +#else
      ExecuteSqlStatement(AH,
                          "SET TRANSACTION ISOLATION LEVEL "
                          "SERIALIZABLE READ ONLY");
  +#endif
  }
  else
      ExecuteSqlStatement(AH,

---

it works if i dump with " --serializable-deferrable" option !

and is there any patch for dump_all ? the dump_all backup tool is important for PGDBAs too.

**Comment by koichi-szk** [comment]
I remembered this patch.   This was not included so far because essential fix is to allow nextval in readonly.   This has to be fixed some day (not too tough).   Then, this patch should be reverted.

Yes, this works anyway.  I'll check if it works both in stable release and master and then update this comment.

Because dump fix is crucial, I will apply this patch to as many branches as possible.   Somebody should remember to revert it when nextval issue is fixed.

Thank you;

Koichi Suzuki

**Comment by koichi-szk** [comment]
The fix was committed so the issue will be closed.

**Comment by xuegang** [comment]
I have reviewed changed code(just removed "read only"). I do not think that it is a good way to fix this bug. Refer to postgres. I think we should not delete "read only". It may bring the bigger problem.

My solution as follows:

```
 Add new catalog procedure getglobalvall. It similar to function nextval(). But getglobalvall just only 
 get last sequence value from gtm.it did not change sequence value. it work well in read only.  then   
 chage function dumpSequenceData in pg_dump.c 
  change select nextval() to select getglobalval();
```

I think it is the better way to fix this problem

Now i have fixed this bug. Test is OK. If you agree with me. I will upload my code.
