### ISSUE TITLE
A bug in pgxc_ctl at datanode_cmd.c

### ISSUE THREAD

**Issue by shenlongxing** [postgres-x2/postgres-x2#87]
I think there is a bug in pgxc_ctl at datanode_cmd.c.

When adding a datanode slave, the datanode master need to restart.
But the host of datanode master in the source code is specified as coordinator master.

The code is as follows:
int
add_datanodeSlave(char *name, char *host, char *dir, char *archDir)
{
    int idx;
    FILE *f;

......

```
/* Restart the master */
/*
 * It's not a good idea to use "restart" here because some connection from other coordinators
 * may be alive.   They are posessed by the pooler and we have to reload the pool to release them,
 * which aborts all the transactions.
 *
 * Beacse we need to issue pgxc_pool_reload() at all the coordinators, we need to give up all the
 * transactions in the whole cluster.
 *
 * It is much better to shutdow the target coordinator master fast because it does not affect
 * transactions this coordinator is not involved.
 */
doImmediate(aval(VAR_coordMasterServers)[idx], NULL, 
            "pg_ctl stop -Z datanode -D %s -m fast", aval(VAR_datanodeMasterDirs)[idx]);
doImmediate(aval(VAR_coordMasterServers)[idx], NULL, 
            "pg_ctl start -Z datanode -D %s -w", aval(VAR_datanodeMasterDirs)[idx]);
```

......
}

I think the correct host is VAR_datanodeMasterServers.

Regards

**Comment by koichi-szk** [comment]
Yes, you are correct.   The fix will go to GitHub promptly.

Thank you very much for pointing out.

Regards;

---

Koichi Suzuki

2015-05-14 13:39 GMT+09:00 Shen Longxing notifications@github.com:

**Comment by koichi-szk** [comment]
The fix was committed both to master and REL1_2_STABLE.

Thank you very much.

**Comment by koichi-szk** [comment]
The fix was committed and the issue will be closed.
